### ISSUE TITLE
Update elements to Bitcoin Core version 0.17.0

### ISSUE THREAD

**Issue by stevenroose** [ElementsProject/elements#398]
- [x] Rebase to or merge from Core v0.17 into elements.
  - [x] 1. Take Bitcoin Core 0.17 branch, at .0 release.
  - [x] In parallel-ish, using a "wiped history" strategy, apply each cleanly, with configurable flags to stay compatible with Bitcoin:
  - [x] 2. Apply custom chains++ arguments (testchains) (@jtimon) #432
  - [x] 3. Apply blocksigning (@instagibbs) #478
  - [x] 4. Apply peg functionality @stevenroose) #458
  - [x] 5. Apply additional op codes (@stevenroose) #495
  - [x] After:
  - [x] 6. CT/CA consensus/policy, with no wallet support (@instagibbs) #503 
  - [x] 7. Issuance consensus/policy (@instagibbs) #503
  - [x] 8. CT/CA wallet functionality (@instagibbs) #503
  - [x] And finally:
  - [x] 9. Peg-out authorization support (@instagibbs) https://github.com/ElementsProject/elements/pull/484
- [x] Update integration tests that make use of changed API functionality.
- [x] height in header #431
- [x] mandatory coinbase destination #430
- [x] connecting coinbase output in genesis block #429
- [x] Moving scriptWitness back into its own witness structure we can expand with other fields, such as peg_in_witness, output witnesses, etc. (@stevenroose) #494
- [x] Get rid of non-segwit serialization format #494
- [x] Parent chains without POW (elements to elements)
- [x] add `initialfreecoins` https://github.com/ElementsProject/elements/pull/467
- [x] `CommitToArguments`? (introduced in db42451290864a0c73e2b80b2ca1f6e08d47031f, edited later)
- [x] mandatory v5 blocks https://github.com/ElementsProject/elements/pull/470
~- [ ] Audit log~ I don't think we want this anymore - Greg
- [x] option for always-on-rbf https://github.com/ElementsProject/elements/pull/481
- [x] Update secp to secp-zkp https://github.com/ElementsProject/elements/pull/482
- [x] forward port of Blockstream/liquid#6 and Blockstream/liquid#8 (with appropriate gating behind g_signed_blocks)
- [x] Liquid v1 fedpeg script support https://github.com/ElementsProject/elements/pull/497
- [x] Segwit/CSV always-on for custom chains. Done upstream in d618458184742b15a7ab0349127ede7a2946a182 https://github.com/ElementsProject/elements/pull/505
Cosmetic/Branching:
- [x] Rename binaries/log messages to elements https://github.com/ElementsProject/elements/pull/521
- [x] default chain becomes elementsregtest https://github.com/ElementsProject/elements/pull/520

**Comment by instagibbs** [comment]
historically we'e rebased on top to keep the history easier to reason about. Open to other strategies of course.

**Comment by instagibbs** [comment]
I'm upgrading this to 0.17.0. I'm thinking of a strategy such as:

1) Take Bitcoin Core 0.17 branch, at .0 release.
In parallel-ish:
2) Apply blocksigning
3) Apply peg functionality
After:
4) CT/CA consensus/policy (configurable chainparams option?), with no wallet support
5) CT/CA wallet functionality, driven by the chainparam option?
And finally:
6) Peg-out authorization support

Each part can basically be done simultaneously in reality aside from 4/5, just requiring some serious rebasing.

**Comment by jtimon** [comment]
I would like to take 2 and 3.

**Comment by instagibbs** [comment]
I'll do 6/7/8. 

@stevenroose 4/5 might be good to do.

**Comment by instagibbs** [comment]
@jtimon I'm thinking we should also apply 9 on top of the rebase, not before. We should just support script descriptors from the start.

**Comment by stevenroose** [comment]
@instagibbs Perfect, 4/5 it is! An adventure for sure :)

**Comment by instagibbs** [comment]
Other assorted tasks:
1) height in header
2) mandatory coinbase destination
3) connecting coinbase output in genesis block https://github.com/ElementsProject/elements/pull/429
4) Moving scriptWitness back into its own witness structure we can expand with other fields, such as peg_in_witness, output witnesses, etc.

**Comment by instagibbs** [comment]
6. Parameterize block subsidy (to set it to 0 by default)

**Comment by luke-jr** [comment]
> option for always-on-rbf

Dunno if you'd prefer to rebase this from the old branch, or it might make more sense to just merge `txrepl_fullrbf` from Knots to simplify?

**Comment by dongcarl** [comment]
@luke-jr this one: https://github.com/bitcoinknots/bitcoin/commit/f5c7ca2cd9c756b03f75ceeff6bb51d82726171f?

**Comment by instagibbs** [comment]
heck if the feature is maintained yes we can just merge it

**Comment by instagibbs** [comment]
Closing as completed. Good work everyone!
