### ISSUE TITLE
Taproot tracking issue

### ISSUE THREAD

**Issue by apoelstra** [ElementsProject/elements#943]
As of the 0.21 rebase we have Taproot in Elements. There is some folowup work we need to make this usable

- [ ] update sighash algorithm (see #933 for design doc)
- [ ] add Taproot to dynafed headers
- [ ] scope out pre-dynafed Taproot in blockheaders; can we softfork it and how much work would this be?
- [ ] add Taproot descriptors (related: descriptors tracking issue)
- [ ] add Simplicity as a Tapleaf (related: simplicity tracking issue)
