### ISSUE TITLE
Descriptors tracking issue

### ISSUE THREAD

**Issue by apoelstra** [ElementsProject/elements#944]
In the 0.21 rebase we have descriptor wallets. There is some followup work we need to do to make this usable

- [ ] publish design doc which adds CT and pegin descriptors
- [ ] add musig and slip77 key wrappers (may require libsecp-zkp update)
- [ ] do Taproot descriptors (ideally we'd copy Core here, but maybe we're ahead of their schedule as they haven't started)
- [ ] update `upgradewallet` RPC for Elements (also not yet done in Core, we can wait for them)
- [ ] Move PAK key management into its own `ScriptPubKeyMan` or otherwise separate it from ordinary wallet keys
